# Generated by Django 4.2 on 2023-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
