# Generated by Django 4.2 on 2023-09-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
