# Generated by Django 4.2 on 2023-09-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_query_name='blogs', to='blog.tag'),
        ),
    ]
